package com.comcast.oscar.examples;

/*
	Copyright 2015 Comcast Cable Communications Management, LLC
	___________________________________________________________________
	Licensed under the Apache License, Version 2.0 (the "License")
	you may not use this file except in compliance with the License.
	You may obtain a copy of the License at
	http://www.apache.org/licenses/LICENSE-2.0
	Unless required by applicable law or agreed to in writing, software
	distributed under the License is distributed on an "AS IS" BASIS,
	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	See the License for the specific language governing permissions and
	limitations under the License.

	@author Maurice Garcia (mgarcia01752@outlook.com)

*/

/*
 *
 * org.json.JSONException: JSONObject["Value"] is not a number.
       at org.json.JSONObject.getDouble(Unknown Source)
       at org.json.JSONObject.getInt(Unknown Source)
       at com.comcast.cpe.cfb.tlv.TlvAssembler.buildTlvFromTlvDictionary(TlvAssembler.java:239)
       at com.comcast.cpe.cfb.tlv.TlvAssembler.buildTlvFromTlvDictionary(TlvAssembler.java:181)
       at com.comcast.cpe.cfb.tlv.TlvAssembler.convertJSONToTLV(TlvAssembler.java:80)
       at com.comcast.cpe.cfb.tlv.TlvAssembler.<init>(TlvAssembler.java:38)
       at test.main(test.java:88)
org.json.JSONException: JSONObject["Value"] is not a number.
       at org.json.JSONObject.getDouble(Unknown Source)
       at org.json.JSONObject.getInt(Unknown Source)
       at com.comcast.cpe.cfb.tlv.TlvAssembler.buildTlvFromTlvDictionary(TlvAssembler.java:239)
       at com.comcast.cpe.cfb.tlv.TlvAssembler.buildTlvFromTlvDictionary(TlvAssembler.java:181)
       at com.comcast.cpe.cfb.tlv.TlvAssembler.buildTlvFromTlvDictionary(TlvAssembler.java:152)
       at com.comcast.cpe.cfb.tlv.TlvAssembler.convertJSONToTLV(TlvAssembler.java:80)
       at com.comcast.cpe.cfb.tlv.TlvAssembler.<init>(TlvAssembler.java:38)
       at test.main(test.java:88)
org.json.JSONException: JSONObject["Value"] is not a number.
       at org.json.JSONObject.getDouble(Unknown Source)
       at org.json.JSONObject.getInt(Unknown Source)
       at com.comcast.cpe.cfb.tlv.TlvAssembler.buildTlvFromTlvDictionary(TlvAssembler.java:239)
       at com.comcast.cpe.cfb.tlv.TlvAssembler.buildTlvFromTlvDictionary(TlvAssembler.java:181)
       at com.comcast.cpe.cfb.tlv.TlvAssembler.buildTlvFromTlvDictionary(TlvAssembler.java:152)
       at com.comcast.cpe.cfb.tlv.TlvAssembler.convertJSONToTLV(TlvAssembler.java:80)
       at com.comcast.cpe.cfb.tlv.TlvAssembler.<init>(TlvAssembler.java:38)
       at test.main(test.java:88)
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 0
       at com.comcast.cpe.cfb.tlv.datatype.DataTypeFormatConversion.hexStringToByte(DataTypeFormatConversion.java:696)
       at com.comcast.cpe.cfb.tlv.TlvAssembler.buildTlvFromTlvDictionary(TlvAssembler.java:523)
       at com.comcast.cpe.cfb.tlv.TlvAssembler.buildTlvFromTlvDictionary(TlvAssembler.java:181)
       at com.comcast.cpe.cfb.tlv.TlvAssembler.convertJSONToTLV(TlvAssembler.java:80)
       at com.comcast.cpe.cfb.tlv.TlvAssembler.<init>(TlvAssembler.java:38)
       at test.main(test.java:88)

 *
 *
 */

import com.comcast.oscar.tlv.TlvAssembler;
import org.json.JSONArray;
import org.json.JSONException;

/** */
public class JsonToHexConvIssue {

  /**
   * @param args
   */
  public static void main(String[] args) {

    String JsonArray =
        "[{\"LevelType\":\"L1\",\"ByteLength\":\"1\",\"TlvName\":\"UpstreamServiceFlow\",\"DataType\":\"integer\",\"Type\":\"24\",\"TlvDescription\":\"This"
            + " field defines the parameters associated with upstream scheduling for a Service"
            + " Flow. It is composed from a\\n"
            + "number of encapsulated type/length/value fields.\\n"
            + "NOTE: The encapsulated upstream and downstream Service Flow configuration setting"
            + " strings share the same\\n"
            + "subtype field numbering plan, because many of the subtype fields defined are valid"
            + " for both types of\\n"
            + "configuration settings. These type fields are not valid in other encoding"
            + " contexts.\",\"SupportedVersion\":\"1.1\",\"Value\":\"\",\"Status\":\"0\",\"CreationDate\":\"20-Nov-2013"
            + " \",\"ParentTypeList\":{\"myArrayList\":[-1,24,43]},\"LengthMax\":0,\"LengthMin\":0,\"AreSubTypes\":true,\"SubTypeArray\":[{\"LevelType\":\"L2\",\"ByteLength\":\"1\",\"TlvName\":\"ServiceFlowReference\",\"DataType\":\"integer\",\"Type\":\"1\",\"TlvDescription\":\"The"
            + " Service Flow Reference is used to associate a packet classifier encoding with a"
            + " Service Flow encoding. A\\n"
            + "Service Flow Reference is only used to establish a Service Flow ID. Once the Service"
            + " Flow exists and has an\\n"
            + "assigned Service Flow ID, the Service Flow Reference MUST no longer be used. The"
            + " Service Flow Reference is\\n"
            + "unique per configuration file, Registration message exchange, or Dynamic Service Add"
            + " message exchange.\\n"
            + "When this sub-TLV 1 is used within TLV 70/71, the value of the field specifies an"
            + " Aggregate Service Flow\\n"
            + "Reference that identifies the Aggregate Service Flow. The ASF Reference is used to"
            + " associate a Service Flow\\n"
            + "encoding with an Aggregate Service Flow encoding.\\n"
            + "An ASF Reference is only used to establish an ASF ID. Once the Aggregate Service"
            + " Flow exists and has an assigned\\n"
            + "Aggregate Service Flow ID, the ASF Reference is no longer be used. The Aggregate"
            + " Service Flow Reference is\\n"
            + "unique per configuration file, Registration message exchange, or Dynamic Service Add"
            + " message"
            + " exchange.\",\"SupportedVersion\":\"1.1\",\"Value\":\"1\",\"Status\":\"0\",\"ParentTypeList\":{\"myArrayList\":[-1,24,1]},\"LengthMax\":2,\"LengthMin\":2,\"AreSubTypes\":false},{\"LevelType\":\"L2\",\"ByteLength\":\"1\",\"TlvName\":\"ServiceFlowIdentifier\",\"DataType\":\"integer\",\"Type\":\"2\",\"TlvDescription\":\"The"
            + " Service Flow Identifier is used by the CMTS as the primary reference of a Service"
            + " Flow. Only the CMTS can\\n"
            + "issue a Service Flow Identifier. It uses this parameterization to issue Service Flow"
            + " Identifiers in CMTS-initiated\\n"
            + "DSA-Requests and in its REG/DSA-Response to CM-initiated REG/DSA-Requests. The CM"
            + " specifies the SFID of a service flow using this parameter in a DSC-REQ message."
            + " Both the CM and CMTS MAY use this TLV to encode\\n"
            + "Service Flow IDs in a DSD-REQ.\\n"
            + "The configuration file MUST NOT contain this"
            + " parameter.\",\"SupportedVersion\":\"1.1\",\"Value\":\"\",\"Status\":\"0\",\"ParentTypeList\":{\"myArrayList\":[-1,24,2]},\"LengthMax\":4,\"LengthMin\":4,\"AreSubTypes\":false},{\"LevelType\":\"L2\",\"ByteLength\":\"1\",\"TlvName\":\"ServiceIdentifier\",\"DataType\":\"byte_array\",\"Type\":\"3\",\"TlvDescription\":\"The"
            + " value of this field specifies the Service Identifier assigned by the CMTS to a"
            + " Service Flow with a non-null\\n"
            + "AdmittedQosParameterSet or ActiveQosParameterSet. This is used in the bandwidth"
            + " allocation MAP to assign\\n"
            + "upstream bandwidth. This field MUST be present in CMTS-initiated DSA-REQ or DSC-REQ"
            + " messages related to\\n"
            + "establishing an admitted or active upstream Service Flow. This field MUST also be"
            + " present in REG-RSP, REGRSP-\\n"
            + "MP, DSA-RSP, and DSC-RSP messages related to the successful establishment of an"
            + " admitted or active\\n"
            + "upstream Service Flow. This field MUST NOT be present in settings related to"
            + " downstream Service Flows; the\\n"
            + "Service Identifier only applies to upstream Service Flows.\\n"
            + "Even though a Service Flow has been successfully admitted or activated (i.e., has an"
            + " assigned Service ID) the\\n"
            + "Service Flow ID MUST be used for subsequent DSx message signaling as it is the"
            + " primary handle for a service\\n"
            + "flow. If a Service Flow is no longer admitted or active (via DSC-REQ) its Service ID"
            + " MAY be reassigned by the\\n"
            + "CMTS.\",\"SupportedVersion\":\"1.1\",\"Value\":\"\",\"Status\":\"0\",\"ParentTypeList\":{\"myArrayList\":[-1,24,3]},\"LengthMax\":2,\"LengthMin\":2,\"AreSubTypes\":false},{\"LevelType\":\"L2\",\"ByteLength\":\"1\",\"TlvName\":\"ServiceClassName\",\"DataType\":\"string_null_terminated\",\"Type\":\"4\",\"TlvDescription\":\"The"
            + " value of the field refers to a predefined CMTS service configuration to be used for"
            + " this Service"
            + " Flow.\",\"SupportedVersion\":\"1.1\",\"Value\":\"silver\",\"Status\":\"0\",\"ParentTypeList\":{\"myArrayList\":[-1,24,4]},\"LengthMax\":16,\"LengthMin\":2,\"AreSubTypes\":false},{\"LevelType\":\"L2\",\"ByteLength\":\"1\",\"TlvName\":\"ServiceFlowError\",\"DataType\":\"integer\",\"Type\":\"5\",\"TlvDescription\":\"This"
            + " field defines the parameters associated with Service Flow Errors. A Service Flow"
            + " Error  consists of a single Service Flow Error Parameter Set which is defined by"
            + " the following individual parameters: Errored Parameter, Confirmation Code and Error"
            + " Message.\",\"SupportedVersion\":\"1.1\",\"Value\":\"\",\"Status\":\"0\",\"ParentTypeList\":{\"myArrayList\":[-1,24,5,3]},\"LengthMax\":0,\"LengthMin\":0,\"AreSubTypes\":true,\"SubTypeArray\":[{\"LevelType\":\"L3\",\"ByteLength\":\"1\",\"TlvName\":\"ErroredParameter\",\"DataType\":\"integer\",\"Type\":\"1\",\"TlvDescription\":\"The"
            + " value of this parameter identifies the subtype of a requested Service Flow"
            + " parameter in error in a rejected\\n"
            + "Service Flow request or Service Class Name expansion response. A Service Flow Error"
            + " Parameter Set MUST have\\n"
            + "exactly one Errored Parameter TLV within a given Service Flow Error"
            + " Encoding.\",\"SupportedVersion\":\"1.1\",\"Value\":\"\",\"Status\":\"0\",\"ParentTypeList\":{\"myArrayList\":[-1,24,5,1]},\"LengthMax\":1,\"LengthMin\":1,\"AreSubTypes\":false},{\"LevelType\":\"L3\",\"ByteLength\":\"1\",\"TlvName\":\"ErrorCode\",\"DataType\":\"integer\",\"Type\":\"2\",\"TlvDescription\":\"This"
            + " parameter indicates the status of the request. A non-zero value corresponds to the"
            + " Confirmation Code as\\n"
            + "described in Annex C.4. A Service Flow Error Parameter Set MUST have exactly one"
            + " Error Code within a given\\n"
            + "Service Flow Error Encoding. A value of okay(0) indicates that the Service Flow"
            + " request was successful. Since a Service Flow Error Parameter Set\\n"
            + "only applies to errored parameters, this value MUST NOT be"
            + " used.\",\"SupportedVersion\":\"1.1\",\"Value\":\"\",\"Status\":\"0\",\"ParentTypeList\":{\"myArrayList\":[-1,24,5,2]},\"LengthMax\":1,\"LengthMin\":1,\"AreSubTypes\":false},{\"LevelType\":\"L3\",\"ByteLength\":\"1\",\"TlvName\":\"ErrorMessage\",\"DataType\":\"string_null_terminated\",\"Type\":\"3\",\"TlvDescription\":\"This"
            + " subtype is optional in a Service Flow Error Parameter Set. If present, it indicates"
            + " a text string to be displayed on\\n"
            + "the CM console and/or log that further describes a rejected Service Flow request. A"
            + " Service Flow Error Parameter\\n"
            + "Set MAY have zero or one Error Message subtypes within a given Service Flow Error"
            + " Encoding.\",\"SupportedVersion\":\"1.1\",\"Value\":\"\",\"Status\":\"0\",\"ParentTypeList\":{\"myArrayList\":[-1,24,5,3]},\"LengthMax\":0,\"LengthMin\":0,\"AreSubTypes\":false}]},{\"LevelType\":\"L2\",\"ByteLength\":\"1\",\"TlvName\":\"QualityOfServiceParameterSetType\",\"DataType\":\"byte\",\"Type\":\"6\",\"TlvDescription\":\"This"
            + " parameter MUST appear within every Service Flow Encoding, with the exception of"
            + " Service Flow Encodings\\n"
            + "in the DSD-REQ where the Quality of Service Parameter Set Type has no value. It"
            + " specifies the proper application\\n"
            + "of the QoS Parameter Set or Service Class Name: to the Provisioned set, the Admitted"
            + " set, and/or the Active set.\\n"
            + "When two QoS Parameter Sets are the same, a multi-bit value of this parameter MAY be"
            + " used to apply the QoS\\n"
            + "parameters to more than one set. A single message MAY contain multiple QoS parameter"
            + " sets in separate type\\n"
            + "24/25 Service Flow Encodings for the same Service Flow. This allows specification of"
            + " the QoS Parameter Sets when\\n"
            + "their parameters are different. Bit 0 is the LSB of the Value field.\\n"
            + "For every Service Flow that appears in a Registration-Request or"
            + " Registration-Response message, there MUST be a\\n"
            + "Service Flow Encoding that specifies a ProvisionedQoSParameterSet. This Service Flow"
            + " Encoding, or other Service\\n"
            + "Flow Encoding(s), MAY also specify an Admitted and/or Active set.\\n"
            + "Any Service Flow Encoding that appears in a Dynamic Service Message MUST NOT specify"
            + " the\\n"
            + "ProvisionedQoSParameterSet.\\n"
            + "Value: \\n"
            + "Bit # 0 Provisioned Set\\n"
            + "Bit # 1 Admitted Set\\n"
            + "Bit # 2 Active Set\\n"
            + "Table C�4 - Values Used in REG-REQ, REG-REQ-MP, REG-RSP, and REG-RSP-MP Messages\\n"
            + "Value Messages\\n"
            + "001 Apply to Provisioned set only\\n"
            + "011 Apply to Provisioned and Admitted set, and perform admission control\\n"
            + "101 Apply to Provisioned and Active sets, perform admission control on Admitted set"
            + " in separate Service\\n"
            + "Flow Encoding, and activate the Service flow.\\n"
            + "111 Apply to Provisioned, Admitted, and Active sets; perform admission control and"
            + " activate this Service\\n"
            + "Flow\\n"
            + "Table C�5 - Values Used In REG-REQ, REG-REQ-MP, REG-RSP,\\n"
            + "REG-RSP-MP, and Dynamic Service Messages\\n"
            + "Value Messages\\n"
            + "010 Perform admission control and apply to Admitted set\\n"
            + "100 Check against Admitted set in separate Service flow Encoding, perform admission"
            + " control if needed,\\n"
            + "activate this Service Flow, and apply to Active set\\n"
            + "110 Perform admission control and activate this Service Flow, apply parameters to"
            + " both Admitted and\\n"
            + "Active sets\\n"
            + "The value 000 is used only in Dynamic Service Change messages. It is used to set the"
            + " Active and Admitted sets to\\n"
            + "Null (see Section 7.5.7.4).\\n"
            + "A CMTS MUST handle a single update to each of the Active and Admitted QoS parameter"
            + " sets. The ability to\\n"
            + "process multiple Service Flow Encodings that specify the same QoS parameter set is"
            + " NOT required, and is left as a\\n"
            + "vendor-specific function. If a DSA/DSC contains multiple updates to a single QoS"
            + " parameter set and the vendor\\n"
            + "does not support such updates, then the CMTS MUST reply with error code 2,"
            + " reject-unrecognized-configurationsetting\\n"
            + "(see Annex"
            + " C.4).\",\"SupportedVersion\":\"1.1\",\"Value\":\"\",\"Status\":\"0\",\"ParentTypeList\":{\"myArrayList\":[-1,24,6]},\"LengthMax\":1,\"LengthMin\":1,\"AreSubTypes\":false},{\"LevelType\":\"L2\",\"ByteLength\":\"1\",\"TlvName\":\"TrafficPriority\",\"DataType\":\"integer\",\"Type\":\"7\",\"TlvDescription\":\"The"
            + " value of this parameter specifies the priority assigned to a Service Flow. The CMTS"
            + " SHOULD provide\\n"
            + "differentiated service based on the value of Traffic Priority. The specific"
            + " algorithm for enforcing this parameter is\\n"
            + "not mandated here. The default priority is 0.\\n"
            + "For upstream service flows, the CMTS SHOULD use this parameter when determining"
            + " precedence in request\\n"
            + "service and grant generation. For upstream service flows, the CM MUST include"
            + " contention Request opportunities\\n"
            + "for Priority Request Service IDs (refer to Annex A.2.3) in its request backoff"
            + " algorithm based on this priority and its\\n"
            + "Request/Transmission Policy (refer to Annex C.2.2.8.3).\\n"
            + "For downstream service flows configured with a non-default value, the CMTS inserts"
            + " this priority as a three bit tag\\n"
            + "into the Downstream Service Extended Header as defined in Section 6.2.5.6. The CM"
            + " preferentially orders the PDU\\n"
            + "packets onto the egress queues based on this 3-bit Traffic Priority in the DS EHDR"
            + " as described in Section"
            + " 7.6.\",\"SupportedVersion\":\"1.1\",\"Value\":\"\",\"Status\":\"0\",\"ParentTypeList\":{\"myArrayList\":[-1,24,7]},\"LengthMax\":1,\"LengthMin\":1,\"AreSubTypes\":false},{\"LevelType\":\"L2\",\"ByteLength\":\"1\",\"TlvName\":\"MaxSubstainedTrafficRate\",\"DataType\":\"integer\",\"Type\":\"8\",\"TlvDescription\":\"This"
            + " parameter is the rate parameter R of a token-bucket-based rate limit for packets. R"
            + " is expressed in bits per\\n"
            + "second, and MUST take into account all MAC frame data PDU of the Service Flow from"
            + " the byte following the\\n"
            + "MAC header HCS to the end of the CRC, including every PDU in the case of a"
            + " Concatenated MAC Frame. This\\n"
            + "parameter is applied after Payload Header Suppression; it does not include the bytes"
            + " suppressed for PHS.\\n"
            + "The number of bytes forwarded (in bytes) is limited during any time interval T by"
            + " Max(T), as described in the\\n"
            + "expression:\\n"
            + "Max(T) \u003d T * (R / 8) + B, (1)\\n"
            + "where the parameter B (in bytes) is the Maximum Traffic Burst Configuration Setting"
            + " (refer to Annex C.2.2.7.3).\\n"
            + "NOTE: This parameter does not limit the instantaneous rate of the Service Flow.\\n"
            + "The specific algorithm for enforcing this parameter is not mandated here. Any"
            + " implementation which satisfies the\\n"
            + "above equation is conformant. In particular, the granularity of enforcement and the"
            + " minimum implemented value of\\n"
            + "this parameter are vendor specific. The CMTS SHOULD support a granularity of at most"
            + " 100 kbps. The CM\\n"
            + "SHOULD support a granularity of at most 100 kbps.\\n"
            + "NOTE: If this parameter is omitted or set to zero, then there is no"
            + " explicitly-enforced traffic rate maximum. This field\\n"
            + "specifies only a bound, not a guarantee that this rate is available. \\n"
            + "\\n"
            + "Upstream Maximum Sustained Traffic Rate\\n"
            + "For an upstream Service Flow, the CM MUST NOT request bandwidth exceeding the Max(T)"
            + " requirement in\\n"
            + "expression (1) during any interval T because this could force the CMTS to fill MAPs"
            + " with deferred grants.\\n"
            + "The CM MUST defer upstream packets that violate expression (1) and \u0027rate"
            + " shape\u0027 them to meet the expression, up\\n"
            + "to a limit defined by the Buffer Control parameter.\\n"
            + "The CMTS MUST enforce expression (1) on all upstream data transmissions, including"
            + " data sent in contention. The\\n"
            + "CMTS MAY consider unused grants in calculations involving this parameter. The CMTS"
            + " MAY enforce this limit\\n"
            + "by any of the following methods: (a) discarding over-limit requests, (b) deferring"
            + " (through zero-length grants) the\\n"
            + "grant until it is conforming to the allowed limit, or (c) discarding over-limit data"
            + " packets. A CMTS MUST report this condition to a policy module. If the CMTS is"
            + " policing by discarding either packets or requests, the CMTS\\n"
            + "MUST allow a margin of error between the CM and CMTS algorithms.\\n"
            + "\\n"
            + "Downstream Maximum Sustained Traffic Rate\\n"
            + "For a downstream Service Flow, this parameter is only applicable at the CMTS. The"
            + " CMTS MUST enforce\\n"
            + "expression (1) on all downstream data transmissions. The CMTS MUST NOT forward"
            + " downstream packets that\\n"
            + "violates expression (1) in any interval T. The CMTS SHOULD \u0027rate shape\u0027"
            + " the downstream traffic by enqueuing\\n"
            + "packets arriving in excess of expression (1), and delay them until the expression"
            + " can be met.\\n"
            + "When a CMTS implements both a Maximum Sustained Traffic Rate and a Peak Downstream"
            + " Traffic Rate for a\\n"
            + "service flow, it limits the bytes forwarded in any interval T to the lesser of"
            + " Max(T) defined in equation (1) and\\n"
            + "Peak(T) defined in equation (2) of Annex C.2.2.9.2.\\n"
            + "This parameter is not intended for enforcement on the"
            + " CM.\",\"SupportedVersion\":\"1.1\",\"Value\":\"\",\"Status\":\"0\",\"ParentTypeList\":{\"myArrayList\":[-1,24,8]},\"LengthMax\":4,\"LengthMin\":4,\"AreSubTypes\":false},{\"LevelType\":\"L2\",\"ByteLength\":\"1\",\"TlvName\":\"MaxTrafficBurst\",\"DataType\":\"integer\",\"Type\":\"9\",\"TlvDescription\":\"The"
            + " value of this parameter specifies the token bucket size B (in bytes) for this"
            + " Service Flow as described in\\n"
            + "expression (1). This value is calculated from the byte following the MAC header HCS"
            + " to the end of the CRC,\\n"
            + "including every PDU in the case of a Concatenated MAC Frame.\\n"
            + "The minimum value of B is 1522 bytes. If this parameter is omitted, the default"
            + " value for B is 3044 bytes. This\\n"
            + "parameter has no effect unless a non-zero value has been provided for the Maximum"
            + " Sustained Traffic Rate\\n"
            + "parameter.\\n"
            + "Bonded downstream packets may be internally distributed across multiple channels"
            + " within the CMTS after they have\\n"
            + "been scheduled according to the rate limiting algorithm in expression (1). As a"
            + " result, the traffic burst observed at\\n"
            + "the CMTS output would not just be a function of the rate limiting algorithm, but"
            + " would also be a function of the\\n"
            + "skew between the channels that data is sent on. Thus the observed traffic burst"
            + " could exceed the Maximum Traffic\\n"
            + "Burst value.\\n"
            + "The resequencing and reassembly operations may also impact the observed maximum"
            + " traffic burst of a downstream\\n"
            + "or upstream bonded service flow. When a stream of packets are resequenced (or"
            + " segments are reassembled) they\\n"
            + "can\u0027t be forwarded until all have arrived (or a timeout occurred). As a result,"
            + " a period of idle time would be followed\\n"
            + "by a traffic burst even if the CMTS/CM performed perfect output shaping of the"
            + " traffic as per (1).\\n"
            + "For an upstream service flow, if B is sufficiently less than the Maximum"
            + " Concatenated Burst parameter, then\\n"
            + "enforcement of the rate limit equation will limit the maximum size of a concatenated"
            + " burst. \\n"
            + "NOTE: The value of this parameter affects the trade-off between the data latency"
            + " perceived by an individual\\n"
            + "application, and the traffic engineering requirements of the network. A large value"
            + " will tend to reduce the\\n"
            + "latency introduced by rate limiting for applications with burst traffic patterns. A"
            + " small value will tend to spread\\n"
            + "out the bursts of data generated by such applications, which may benefit traffic"
            + " engineering within the\\n"
            + "network.\",\"SupportedVersion\":\"1.1\",\"Value\":\"\",\"Status\":\"0\",\"ParentTypeList\":{\"myArrayList\":[-1,24,9]},\"LengthMax\":4,\"LengthMin\":4,\"AreSubTypes\":false},{\"LevelType\":\"L2\",\"ByteLength\":\"1\",\"TlvName\":\"MinReservedTrafficRate\",\"DataType\":\"integer\",\"Type\":\"10\",\"TlvDescription\":\"This"
            + " parameter specifies the minimum rate, in bits/sec, reserved for this Service Flow."
            + " The value of this parameter is\\n"
            + "calculated from the byte following the MAC header HCS to the end of the CRC,"
            + " including every PDU in a\\n"
            + "Concatenated MAC Frame. If this parameter is omitted, then it defaults to a value of"
            + " 0 bits/sec (i.e., no bandwidth is\\n"
            + "reserved for the flow by default).\\n"
            + "How Minimum Reserved Traffic Rate and Assumed Minimum Reserved Rate Packet Size"
            + " apply to a CMTS\u0027s\\n"
            + "admission control policies is vendor specific, and is beyond the scope of this"
            + " specification. The aggregate Minimum\\n"
            + "Reserved Traffic Rate of all Service Flows could exceed the amount of available"
            + " bandwidth.\\n"
            + "Unless explicitly configured otherwise, a CMTS SHOULD schedule forwarding of all"
            + " service flows\u0027 traffic such that\\n"
            + "each receives at least its Minimum Reserved Traffic Rate when transmitting packets"
            + " with the Assumed Minimum\\n"
            + "Reserved Rate Packet Size. If the service flow sends packets of a size smaller than"
            + " the Assumed Minimum Reserved\\n"
            + "Rate Packet Size, such packets will be treated as being of the Assumed Minimum"
            + " Reserved Rate Packet Size for\\n"
            + "calculating the rate forwarded from the service flow for purposes of meeting the"
            + " Minimum Reserved Traffic Rate. If\\n"
            + "less bandwidth than its Minimum Reserved Traffic Rate is requested for a Service"
            + " Flow, the CMTS MAY reallocate\\n"
            + "the excess reserved bandwidth for other purposes.\\n"
            + "NOTE: The granularity of the Minimum Reserved Traffic Rate used internally by the"
            + " CMTS is vendor specific.\\n"
            + "Because of this, the CMTS MAY schedule forwarding of a service flow\u0027s traffic"
            + " at a rate greater than the\\n"
            + "configured value for Minimum Reserved Traffic Rate.\\n"
            + "This field is only applicable at the"
            + " CMTS.\",\"SupportedVersion\":\"1.1\",\"Value\":\"\",\"Status\":\"0\",\"ParentTypeList\":{\"myArrayList\":[-1,24,10]},\"LengthMax\":4,\"LengthMin\":4,\"AreSubTypes\":false},{\"LevelType\":\"L2\",\"ByteLength\":\"1\",\"TlvName\":\"AssumedMinReserved"
            + " RatePacketSize\",\"DataType\":\"integer\",\"Type\":\"11\",\"TlvDescription\":\"This"
            + " parameter is used by the CMTS to make worst-case DOCSIS overhead assumptions. The"
            + " Minimum Reserved\\n"
            + "Traffic Rate of a service flow excludes the DOCSIS MAC header and any other DOCSIS"
            + " overhead (e.g., for\\n"
            + "completing an upstream mini-slot). Traffic with smaller packets sizes will require a"
            + " higher proportion of overall\\n"
            + "channel capacity for DOCSIS overhead than traffic with larger packet sizes. The CMTS"
            + " assumes that the worst-case\\n"
            + "DOCSIS overhead for a service flow will be when all traffic is as small as the size"
            + " specified in this parameter.\\n"
            + "This parameter is defined in bytes and is specified as the bytes following the MAC"
            + " header HCS to the end of the\\n"
            + "CRC.\\n"
            + "If this parameter is omitted, then the default value is CMTS implementation"
            + " dependent.\",\"SupportedVersion\":\"1.1\",\"Value\":\"\",\"Status\":\"0\",\"ParentTypeList\":{\"myArrayList\":[-1,24,11]},\"LengthMax\":2,\"LengthMin\":2,\"AreSubTypes\":false},{\"LevelType\":\"L2\",\"ByteLength\":\"1\",\"TlvName\":\"TimeoutForActiveQoS\",\"DataType\":\"integer\",\"Type\":\"12\",\"TlvDescription\":\"The"
            + " value of this parameter specifies the maximum duration resources remain unused on"
            + " an active Service Flow. If\\n"
            + "there is no activity on the Service Flow within this time interval, the CMTS MUST"
            + " change the active and admitted\\n"
            + "QoS Parameter Sets to null. The CMTS MUST signal this resource change with a DSC-REQ"
            + " to the CM. The value of this parameter specifies the maximum duration resources"
            + " remain unused on an active Service Flow. If\\n"
            + "there is no activity on the Service Flow within this time interval, the CMTS MUST"
            + " change the active and admitted\\n"
            + "QoS Parameter Sets to null. The CMTS MUST signal this resource change with a DSC-REQ"
            + " to the"
            + " CM.\",\"SupportedVersion\":\"1.1\",\"Value\":\"\",\"Status\":\"0\",\"ParentTypeList\":{\"myArrayList\":[-1,24,12]},\"LengthMax\":2,\"LengthMin\":2,\"AreSubTypes\":false},{\"LevelType\":\"L2\",\"ByteLength\":\"1\",\"TlvName\":\"TimeoutForAdmittedQoS\",\"DataType\":\"integer\",\"Type\":\"13\",\"TlvDescription\":\"The"
            + " value of this parameter specifies the duration that the CMTS MUST hold resources"
            + " for a Service Flow\u0027s\\n"
            + "Admitted QoS Parameter Set while they are in excess of its Active QoS Parameter Set."
            + " If there is no DSC-REQ to\\n"
            + "activate the Admitted QoS Parameter Set within this time interval, and there is no"
            + " DSC to refresh the QoS parameter\\n"
            + "sets and restart the timeout (see Section 7.5.5.2), the resources that are admitted"
            + " but not activated MUST be released,\\n"
            + "and only the active resources retained. The CMTS MUST set the Admitted QoS Parameter"
            + " Set equal to the\\n"
            + "Active QoS Parameter Set for the Service Flow and initiate a DSC-REQ exchange with"
            + " the CM to inform it of the\\n"
            + "change.\\n"
            + "This parameter MUST be enforced at the CMTS. This parameter SHOULD NOT be enforced"
            + " at the CM. The\\n"
            + "parameter is processed by the CMTS for every QoS set contained in Registration"
            + " messages and Dynamic Service\\n"
            + "messages. If the parameter is omitted, the default of 200 seconds is assumed. A"
            + " value of 0 means that the Service\\n"
            + "Flow can remain in the admitted state for an infinite amount of time and MUST NOT be"
            + " timed out due to inactivity.\\n"
            + "However, this is subject to policy control by the CMTS. The value specified for the"
            + " active QoS set must be less than\\n"
            + "or equal to the corresponding value in the admitted QoS set which must be less than"
            + " or equal to the corresponding\\n"
            + "value in the provisioned/authorized QoS set. If the requested value is too large,"
            + " the CMTS MAY reject the message\\n"
            + "or respond with a value less than that requested. If the Registration or Dynamic"
            + " Service message containing this\\n"
            + "parameter is accepted by the CMTS and acknowledged by the CM, the Admitted QoS"
            + " Timeout timer is loaded with\\n"
            + "the new value of the timeout. The timer is activated if the message admits resources"
            + " greater than the active set. The\\n"
            + "timer is deactivated if the message sets the active QoS set and admitted QoS set"
            + " equal to each"
            + " other.\",\"SupportedVersion\":\"1.1\",\"Value\":\"\",\"Status\":\"0\",\"ParentTypeList\":{\"myArrayList\":[-1,24,13]},\"LengthMax\":2,\"LengthMin\":2,\"AreSubTypes\":false},{\"LevelType\":\"L2\",\"ByteLength\":\"1\",\"TlvName\":\"MaxConcatenatedBurst\",\"DataType\":\"integer\",\"Type\":\"14\",\"TlvDescription\":\"The"
            + " value of this parameter specifies the maximum concatenated burst (in bytes) which a"
            + " Service Flow is allowed\\n"
            + "when not operating in MTC Mode. This parameter is calculated from the FC byte of the"
            + " Concatenation MAC\\n"
            + "Header to the last CRC in the concatenated MAC frame.\\n"
            + "A value of 0 means there is no limit. If this parameter is omitted the default value"
            + " is 1522.\\n"
            + "This field is only applicable at the CM. If defined, this parameter MUST be enforced"
            + " at the CM.\\n"
            + "NOTE: This value does not include any physical layer overhead.\\n"
            + "\\n"
            + "NOTE: This applies only to concatenated bursts, and only when the CM is not"
            + " operating in MTC Mode. It is legal\\n"
            + "and, in fact, it may be useful to set this smaller than the maximum Ethernet packet"
            + " size. Of course, it is also\\n"
            + "legal to set this equal to or larger than the maximum Ethernet packet size.\\n"
            + "NOTE: The maximum size of a concatenated burst can also be limited by the"
            + " enforcement of a rate limit, if the\\n"
            + "Maximum Traffic Burst parameter is small enough, and by limits on the size of data"
            + " grants in the UCD\\n"
            + "message.\",\"SupportedVersion\":\"1.1\",\"Value\":\"\",\"Status\":\"0\",\"ParentTypeList\":{\"myArrayList\":[-1,24,14]},\"LengthMax\":2,\"LengthMin\":2,\"AreSubTypes\":false},{\"LevelType\":\"L2\",\"ByteLength\":\"1\",\"TlvName\":\"SchedulingType\",\"DataType\":\"integer\",\"Type\":\"15\",\"TlvDescription\":\"The"
            + " value of this parameter specifies which upstream scheduling service is used for"
            + " upstream transmission requests\\n"
            + "and packet transmissions. If this parameter is omitted, then the Best Effort service"
            + " MUST be assumed.\\n"
            + "This parameter is only applicable at the CMTS. If defined, this parameter MUST be"
            + " enforced by the CMTS. \\n"
            + "Value:\\n"
            + "0 Reserved\\n"
            + "1 for Undefined (CMTS implementation-dependent1)\\n"
            + "2 for Best Effort\\n"
            + "3 for Non-Real-Time Polling Service\\n"
            + "4 for Real-Time Polling Service\\n"
            + "5 for Unsolicited Grant Service with Activity Detection\\n"
            + "6 for Unsolicited Grant Service\\n"
            + "7 through 255 are reserved for future use\\n"
            + "Note 1 The specific implementation dependent scheduling service type could be"
            + " defined in the 24.43 Vendor Specific QoS\\n"
            + "Parameters. (Refer to Annex"
            + " C.2.2.7.8.)\",\"SupportedVersion\":\"1.1\",\"Value\":\"\",\"Status\":\"0\",\"ParentTypeList\":{\"myArrayList\":[-1,24,15]},\"LengthMax\":1,\"LengthMin\":1,\"AreSubTypes\":false},{\"LevelType\":\"L2\",\"ByteLength\":\"1\",\"TlvName\":\"RequestTransmissionPolicy\",\"DataType\":\"string_bits\",\"Type\":\"16\",\"TlvDescription\":\"The"
            + " value of this parameter specifies which IUC opportunities the CM uses for upstream"
            + " transmission requests and\\n"
            + "packet transmissions for this Service Flow, whether requests for this Service Flow"
            + " may be piggybacked with data,\\n"
            + "and whether data packets transmitted on this Service Flow can be concatenated,"
            + " fragmented, or have their payload\\n"
            + "headers suppressed. For UGS, it also specifies how to treat packets that do not fit"
            + " into the UGS grant. See Section\\n"
            + "7.2.3 for requirements related to settings of the bits of this parameter for each"
            + " Service Flow Scheduling Type. For\\n"
            + "Continuous Concatenation and Fragmentation, it specifies whether or not segment"
            + " headers are used, and what\\n"
            + "opportunities can be used for making bandwidth requests.\\n"
            + "This parameter is required for all Service Flow Scheduling Types except Best Effort."
            + " If omitted in a Best Effort\\n"
            + "Service Flow QoS parameter Set, the default value of zero MUST be used. Bit #0 is"
            + " the LSB of the Value field. Bits\\n"
            + "are set to 1 to select the behavior defined below: \\n"
            + "Bit #0 The Service Flow MUST NOT use \u0027all CMs\u0027 broadcast request"
            + " opportunities.\\n"
            + "Bit #1 The Service Flow MUST NOT use Priority Request multicast request"
            + " opportunities. (Refer to\\n"
            + "Annex A.2.3.)\\n"
            + "Bit #2 The Service Flow MUST NOT use Request/Data opportunities for Requests.\\n"
            + "Bit #3 The Service Flow MUST NOT use Request/Data opportunities for Data. 1\\n"
            + "Bit #4 The Service Flow MUST NOT piggyback requests with data.\\n"
            + "Bit #5 The Service Flow MUST NOT concatenate data.2\\n"
            + "Bit #6 The Service Flow MUST NOT fragment data.\\n"
            + "Bit #7 The Service Flow MUST NOT suppress payload headers.\\n"
            + "Bit #8 The Service Flow MUST drop packets that do not fit in the Unsolicited Grant"
            + " Size. 3,4\\n"
            + "Bit #9 The Service Flow MUST NOT use segment headers. When set to zero, the Service"
            + " Flow\\n"
            + "MUST use segment headers.5\\n"
            + "Bit #10 The Service Flow MUST NOT use contention regions for transmitting multiple"
            + " outstanding\\n"
            + "bandwidth requests.\\n"
            + "All other bits are reserved.\\n"
            + "1 This bit is irrelevant for a CM in Multiple Transmit Channel Mode because it does"
            + " not use Request/Data for sending data.\\n"
            + "2 This bit applies for pre-3.0 DOCSIS operation.\\n"
            + "3 This bit only applies to Service Flows with the Unsolicited Grant Service Flow"
            + " Scheduling Type. If this bit is set on any other\\n"
            + "Service Flow Scheduling type, it MUST be ignored.\\n"
            + "4 Packets that classify to an Unsolicited Grant Service Flow and are larger than the"
            + " Grant Size associated with that Service Flow\\n"
            + "are normally transmitted on the Primary Service Flow. This parameter overrides that"
            + " default behavior.\\n"
            + "5 Only UGS or UGS-AD Service Flows can be configured with Segment Header OFF for CMs"
            + " operating in Multiple Transmit\\n"
            + "Channel Mode.\\n"
            + "NOTE: Data grants include both short and long data"
            + " grants.\",\"SupportedVersion\":\"1.1\",\"Value\":\"\",\"Status\":\"0\",\"ParentTypeList\":{\"myArrayList\":[-1,24,16]},\"LengthMax\":4,\"LengthMin\":4,\"AreSubTypes\":false},{\"LevelType\":\"L2\",\"ByteLength\":\"1\",\"TlvName\":\"NominalPollingInterval\",\"DataType\":\"integer\",\"Type\":\"17\",\"TlvDescription\":\"The"
            + " value of this parameter specifies the nominal interval (in units of microseconds)"
            + " between successive unicast\\n"
            + "request opportunities for this Service Flow on the upstream channel. This parameter"
            + " is typically suited for Real-\\n"
            + "Time and Non-Real-Time Polling Service.\\n"
            + "The ideal schedule for enforcing this parameter is defined by a reference time t0,"
            + " with the desired transmission times\\n"
            + "ti \u003d t0 + i*interval. The actual poll times, t\u0027i MUST be in the range ti"
            + " \u003c\u003d t\u0027i \u003c\u003d ti + jitter, where interval is the value\\n"
            + "specified with this TLV, and jitter is Tolerated Poll Jitter. The accuracy of the"
            + " ideal poll times, ti, are measured\\n"
            + "relative to the CMTS Master Clock used to generate timestamps (refer to Section"
            + " 7.1).\\n"
            + "This field is only applicable at the CMTS. If defined, this parameter MUST be"
            + " enforced by the"
            + " CMTS.\",\"SupportedVersion\":\"1.1\",\"Value\":\"\",\"Status\":\"0\",\"ParentTypeList\":{\"myArrayList\":[-1,24,17]},\"LengthMax\":4,\"LengthMin\":4,\"AreSubTypes\":false},{\"LevelType\":\"L2\",\"ByteLength\":\"1\",\"TlvName\":\"ToleratedPollJitter\",\"DataType\":\"integer\",\"Type\":\"18\",\"TlvDescription\":\"The"
            + " values in this parameter specifies the maximum amount of time that the unicast"
            + " request interval may be delayed\\n"
            + "from the nominal periodic schedule (measured in microseconds) for this Service"
            + " Flow.\\n"
            + "The ideal schedule for enforcing this parameter is defined by a reference time t0,"
            + " with the desired poll times ti \u003d t0 +\\n"
            + "i*interval. The actual poll, t\u0027i MUST be in the range ti \u003c\u003d t\u0027i"
            + " \u003c\u003d ti + jitter, where jitter is the value specified with this\\n"
            + "TLV and interval is the Nominal Poll Interval. The accuracy of the ideal poll times,"
            + " ti, are measured relative to the\\n"
            + "CMTS Master Clock used to generate timestamps (refer to Section 7.1).\\n"
            + "This parameter is only applicable at the CMTS. If defined, this parameter represents"
            + " a service commitment (or\\n"
            + "admission criteria) at the"
            + " CMTS.\",\"SupportedVersion\":\"1.1\",\"Value\":\"\",\"Status\":\"0\",\"ParentTypeList\":{\"myArrayList\":[-1,24,18]},\"LengthMax\":4,\"LengthMin\":4,\"AreSubTypes\":false},{\"LevelType\":\"L2\",\"ByteLength\":\"1\",\"TlvName\":\"UnsolicitedGrantSize\",\"DataType\":\"integer\",\"Type\":\"19\",\"TlvDescription\":\"The"
            + " value of this parameter specifies the unsolicited grant size in bytes. The grant"
            + " size includes the entire MAC\\n"
            + "frame beginning with the Frame Control byte for Segment Header OFF operation or the"
            + " first byte of the Segment\\n"
            + "Header for Segment Header ON operation, and ending at the end of the MAC frame. This"
            + " parameter is applicable at the CMTS and MUST be enforced at the CMTS. NOTE: For"
            + " UGS, this parameter should be used by the CMTS to compute the size of the"
            + " unsolicited grant in"
            + " minislots.\",\"SupportedVersion\":\"1.1\",\"Value\":\"\",\"Status\":\"0\",\"ParentTypeList\":{\"myArrayList\":[-1,24,19]},\"LengthMax\":2,\"LengthMin\":2,\"AreSubTypes\":false},{\"LevelType\":\"L2\",\"ByteLength\":\"1\",\"TlvName\":\"NominalGrantInterval\",\"DataType\":\"integer\",\"Type\":\"20\",\"TlvDescription\":\"The"
            + " value of this parameter specifies the nominal interval (in units of microseconds)"
            + " between successive data grant\\n"
            + "opportunities for this Service Flow. This parameter is required for Unsolicited"
            + " Grant and Unsolicited Grant with\\n"
            + "Activity Detection Service Flows. The ideal schedule for enforcing this parameter is"
            + " defined by a reference time t0, with the desired transmission times\\n"
            + "ti \u003d t0 + i*interval. The actual grant times, t\u0027i MUST be in the range ti"
            + " \u003c\u003d t\u0027i \u003c\u003d ti + jitter, where interval is the value\\n"
            + "specified with this TLV, and jitter is the Tolerated Grant Jitter. When multiple"
            + " grants per interval are requested, all\\n"
            + "grants MUST be within this interval, thus the Nominal Grant Interval and Tolerated"
            + " Grant Jitter are maintained by\\n"
            + "the CMTS for all grants in this Service Flow. The accuracy of the ideal grant times,"
            + " ti, are measured relative to the\\n"
            + "CMTS Master Clock used to generate timestamps (refer to Section 7.1). This field is"
            + " mandatory for Unsolicited Grant and Unsolicited Grant with Activity Detection"
            + " Scheduling Types. This field is only applicable at the CMTS, and MUST be enforced"
            + " by the"
            + " CMTS.\",\"SupportedVersion\":\"1.1\",\"Value\":\"\",\"Status\":\"0\",\"ParentTypeList\":{\"myArrayList\":[-1,24,20]},\"LengthMax\":4,\"LengthMin\":4,\"AreSubTypes\":false},{\"LevelType\":\"L2\",\"ByteLength\":\"1\",\"TlvName\":\"ToleratedGrantJitter\",\"DataType\":\"integer\",\"Type\":\"21\",\"TlvDescription\":\"The"
            + " values in this parameter specifies the maximum amount of time that the transmission"
            + " opportunities may be\\n"
            + "delayed from the nominal periodic schedule (measured in microseconds) for this"
            + " Service Flow.\\n"
            + "The ideal schedule for enforcing this parameter is defined by a reference time t0,"
            + " with the desired transmission times\\n"
            + "ti \u003d t0 + i*interval. The actual transmission opportunities, t\u0027i MUST be"
            + " in the range ti \u003c\u003d t\u0027i \u003c\u003d ti + jitter, where jitter\\n"
            + "is the value specified with this TLV and interval is the Nominal Grant Interval. The"
            + " accuracy of the ideal grant\\n"
            + "times, ti, are measured relative to the CMTS Master Clock used to generate"
            + " timestamps (refer to Section 7.1).\\n"
            + "This field is mandatory for Unsolicited Grant and Unsolicited Grant with Activity"
            + " Detection Scheduling Types. This\\n"
            + "field is only applicable at the CMTS, and MUST be enforced by the"
            + " CMTS.\",\"SupportedVersion\":\"1.1\",\"Value\":\"\",\"Status\":\"0\",\"ParentTypeList\":{\"myArrayList\":[-1,24,21]},\"LengthMax\":4,\"LengthMin\":4,\"AreSubTypes\":false},{\"LevelType\":\"L2\",\"ByteLength\":\"1\",\"TlvName\":\"GrantsPerInterval\",\"DataType\":\"integer\",\"Type\":\"22\",\"TlvDescription\":\"For"
            + " Unsolicited Grant Service, the value of this parameter indicates the actual number"
            + " of data grants per Nominal\\n"
            + "Grant Interval. For Unsolicited Grant Service with Activity Detection, the value of"
            + " this parameter indicates the\\n"
            + "maximum number of Active Grants per Nominal Grant Interval. This is intended to"
            + " enable the addition of sessions\\n"
            + "to an existing Unsolicited Grant Service Flow via the Dynamic Service Change"
            + " mechanism, without negatively\\n"
            + "impacting existing sessions.\\n"
            + "The ideal schedule for enforcing this parameter is defined by a reference time t0,"
            + " with the desired transmission times\\n"
            + "ti \u003d t0 + i*interval. The actual grant times, t\u0027i MUST be in the range ti"
            + " \u003c\u003d t\u0027i \u003c\u003d ti + jitter, where interval is the\\n"
            + "Nominal Grant Interval, and jitter is the Tolerated Grant Jitter. When multiple"
            + " grants per interval are requested, all grants MUST be within this interval, thus"
            + " the Nominal Grant Interval and Tolerated Grant Jitter are maintained by\\n"
            + "the CMTS for all grants in this Service Flow. 633\\n"
            + "This field is mandatory for Unsolicited Grant and Unsolicited Grant with Activity"
            + " Detection Scheduling Types. This\\n"
            + "field is only applicable at the CMTS, and MUST be enforced by the"
            + " CMTS.\",\"SupportedVersion\":\"1.1\",\"Value\":\"\",\"Status\":\"0\",\"ParentTypeList\":{\"myArrayList\":[-1,24,22]},\"LengthMax\":1,\"LengthMin\":1,\"AreSubTypes\":false},{\"LevelType\":\"L2\",\"ByteLength\":\"1\",\"TlvName\":\"IPTypeOfServiceDSCPOverwrite\",\"DataType\":\"integer\",\"Type\":\"23\",\"TlvDescription\":\"The"
            + " CMTS MUST overwrite IP packets with IPv4 TOS byte or IPv6 Traffic Class value"
            + " \u0027orig-ip-tos\u0027 with the value\\n"
            + "\u0027new-ip-tos\u0027, where new-ip-tos \u003d ((orig-ip-tos AND tos-and-mask) OR"
            + " tos-or-mask). If this parameter is omitted,\\n"
            + "then the IP packet TOS/Traffic Class byte is not overwritten.\\n"
            + "\\n"
            + "This parameter is only applicable at the CMTS. If defined, this parameter MUST be"
            + " enforced by the CMTS.\\n"
            + "The IPv4 TOS octet as originally defined in RFC 791 has been superseded by the 6-bit"
            + " Differentiated Services Field\\n"
            + "(DSField, [RFC 3260]) and the 2-bit Explicit Congestion Notification Field (ECN"
            + " field, [RFC 3168]). The IPv6\\n"
            + "Traffic Class octet [RFC 2460] is consistent with that new definition. Network"
            + " operators should avoid specifying\\n"
            + "values of tos-and-mask and tos-or-mask that would result in the modification of the"
            + " ECN bits.\\n"
            + "In particular, operators should not use values of tos-and-mask that have either of"
            + " the least-significant two bits set to\\n"
            + "0. Similarly, operators should not use values of tos-or-mask that have either of the"
            + " least-significant two bits set to"
            + " 1.\",\"SupportedVersion\":\"1.1\",\"Value\":\"\",\"Status\":\"0\",\"ParentTypeList\":{\"myArrayList\":[-1,24,23]},\"LengthMax\":2,\"LengthMin\":2,\"AreSubTypes\":false},{\"LevelType\":\"L2\",\"ByteLength\":\"1\",\"TlvName\":\"UnsolicitedGrantTimeReference\",\"DataType\":\"integer\",\"Type\":\"24\",\"TlvDescription\":\"For"
            + " Unsolicited Grant Service and Unsolicited Grant Service with Activity Detection,"
            + " the value of this parameter\\n"
            + "specifies a reference time t0 from which can be derived the desired transmission"
            + " times ti \u003d t0 + i*interval, where\\n"
            + "interval is the Nominal Grant Interval (Refer to Annex C.2.2.8.7). This parameter is"
            + " applicable only for messages\\n"
            + "transmitted from the CMTS to the CM, and only when a UGS or UGS-AD service flow is"
            + " being made active. In\\n"
            + "such cases this is a mandatory parameter. The timestamp specified in this parameter"
            + " represents a count state of the CMTS 10.24 MHz master clock. Since a\\n"
            + "UGS or UGS-AD service flow is always activated before transmission of this parameter"
            + " to the modem, the reference\\n"
            + "time t0 is to be interpreted by the modem as the ideal time of the next grant only"
            + " if t0 follows the current time. If t0\\n"
            + "precedes the current time, the modem can calculate the offset from the current time"
            + " to the ideal time of the next\\n"
            + "grant according to:\\n"
            + "interval - (((current time - t0)/10.24) modulus interval)\\n"
            + "where interval is in units of microseconds, and current time and t0 are in 10.24 MHz"
            + " units.\",\"SupportedVersion\":\"1.1\",\"Value\":\"\",\"Status\":\"0\",\"ParentTypeList\":{\"myArrayList\":[-1,24,24]},\"LengthMax\":4,\"LengthMin\":4,\"AreSubTypes\":false},{\"LevelType\":\"L2\",\"ByteLength\":\"1\",\"TlvName\":\"MultiplierContentionBackoffWindow\",\"DataType\":\"integer\",\"Type\":\"25\",\"TlvDescription\":\"In"
            + " 3.0 operation, this is a multiplier to be applied by a CM performing contention"
            + " request backoff for data requests.\\n"
            + "Section 7.2.1.5 contains the details on how this multiplier is applied. This setting"
            + " is not included in a CM\\n"
            + "configuration file. The CMTS MAY include this setting whenever it provides a CM the"
            + " parameters associated with a\\n"
            + "service flow. If this parameter is not encoded, the parameter value is assumed to be"
            + " 8, and thus, the multiplier is equal to 1. If the\\n"
            + "received value is outside the valid range, the CM MUST assume a value of 8, and"
            + " thus, the multiplier is equal to"
            + " 1.\",\"SupportedVersion\":\"3\",\"Value\":\"\",\"Status\":\"0\",\"ParentTypeList\":{\"myArrayList\":[-1,24,25]},\"LengthMax\":1,\"LengthMin\":1,\"AreSubTypes\":false},{\"LevelType\":\"L2\",\"ByteLength\":\"1\",\"TlvName\":\"MultiplierNumberOfBytesRequested\",\"DataType\":\"integer\",\"Type\":\"26\",\"TlvDescription\":\"In"
            + " 3.0 operation, this is a multiplier to be assumed in any bandwidth request (REQ"
            + " burst or piggyback request).\\n"
            + "Section 7.2.1.4 contains the details on how this multiplier is applied. If this"
            + " parameter is not encoded, the default value of 4 is"
            + " used.\",\"SupportedVersion\":\"3\",\"Value\":\"\",\"Status\":\"0\",\"ParentTypeList\":{\"myArrayList\":[-1,24,26]},\"LengthMax\":1,\"LengthMin\":1,\"AreSubTypes\":false},{\"LevelType\":\"L2\",\"ByteLength\":\"1\",\"TlvName\":\"UpstreamPeakTrafficRate\",\"DataType\":\"integer\",\"Type\":\"27\",\"TlvDescription\":\"For"
            + " an upstream Service Flow, the CM SHOULD NOT request bandwidth exceeding the Peak(T)"
            + " requirement in\\n"
            + "expression (2) during any interval T because this could force the CMTS to discard"
            + " packets and/or fill MAPs with\\n"
            + "deferred grants.\\n"
            + "The CM SHOULD defer upstream packets that violate expression (2) and \u0027rate"
            + " shape\u0027 them to meet the expression,\\n"
            + "up to a limit defined by the Buffer Control parameter.\\n"
            + "The CMTS SHOULD enforce expression (2) on all upstream data transmissions, including"
            + " data sent in\\n"
            + "contention. The CMTS MAY consider unused grants in calculations involving this"
            + " parameter. The CMTS MAY\\n"
            + "enforce this limit by any of the following methods: (a) discarding over-limit"
            + " requests, (b) deferring (through zerolength\\n"
            + "grants) the grant until it is conforming to the allowed limit, or (c) discarding"
            + " over-limit data packets. A\\n"
            + "CMTS SHOULD report this condition to a policy module. If the CMTS is policing by"
            + " discarding either packets or\\n"
            + "requests, the CMTS MUST allow a margin of error between the CM and CMTS"
            + " algorithms.\",\"SupportedVersion\":\"3\",\"Value\":\"\",\"Status\":\"0\",\"ParentTypeList\":{\"myArrayList\":[-1,24,27]},\"LengthMax\":4,\"LengthMin\":4,\"AreSubTypes\":false},{\"LevelType\":\"L2\",\"ByteLength\":\"1\",\"TlvName\":\"ServiceFlowRequiredAttrMask\",\"DataType\":\"byte_array\",\"Type\":\"31\",\"TlvDescription\":\"This"
            + " parameter is optional in upstream and downstream service flows. If specified, it"
            + " limits the set of channels and\\n"
            + "bonding groups to which the CMTS assigns the service flow requiring certain Cable"
            + " Operator-determined binary\\n"
            + "attributes. When this TLV is not present in the service flow request the CMTS"
            + " defaults this value to zero. See Section 8.1.1 for how the Service Flow Required"
            + " Attribute mask, Service Flow Forbidden Attribute Mask, and\\n"
            + "Service Flow Attribute Aggregation Rule Mask control how service flows may be"
            + " assigned to particular channels or\\n"
            + "bonding"
            + " groups.\",\"SupportedVersion\":\"1.1\",\"Value\":\"\",\"Status\":\"0\",\"ParentTypeList\":{\"myArrayList\":[-1,24,31]},\"LengthMax\":4,\"LengthMin\":4,\"AreSubTypes\":false},{\"LevelType\":\"L2\",\"ByteLength\":\"1\",\"TlvName\":\"ServiceFlowForbiddenAttrMask\",\"DataType\":\"byte_array\",\"Type\":\"32\",\"TlvDescription\":\"This"
            + " parameter is optional in upstream and downstream service flows. If specified, it"
            + " limits the set of channels and\\n"
            + "bonding groups to which the CMTS assigns the service flow by forbidding certain"
            + " attributes. When this TLV is not\\n"
            + "present in the service flow request the CMTS defaults this value to zero. See"
            + " Section 8.1.1 for how the Service Flow Required Attribute mask, Service Flow"
            + " Forbidden Attribute Mask, and\\n"
            + "Service Flow Attribute Aggregation Rule Mask control how service flows may be"
            + " assigned to particular channels or\\n"
            + "bonding"
            + " groups.\",\"SupportedVersion\":\"1.1\",\"Value\":\"\",\"Status\":\"0\",\"ParentTypeList\":{\"myArrayList\":[-1,24,32]},\"LengthMax\":4,\"LengthMin\":4,\"AreSubTypes\":false},{\"LevelType\":\"L2\",\"ByteLength\":\"1\",\"TlvName\":\"ServiceFlowAttrAggregationRuleMask\",\"DataType\":\"byte_array\",\"Type\":\"33\",\"TlvDescription\":\"This"
            + " parameter is optional in upstream and downstream service flows. It controls, on a"
            + " per-attribute basis, whether\\n"
            + "the attribute is required or forbidden on any or all channels of a bonding group"
            + " that aggregates multiple channels. It\\n"
            + "can be considered to control how an \u0027aggregate\u0027 attribute mask for the"
            + " bonding group is built by either AND\u0027ing or\\n"
            + "OR\u0027ing the attributes of individual channels of the bonding group. When this"
            + " TLV is not present in the service flow\\n"
            + "request the CMTS defaults this value to zero.\\n"
            + "\\n"
            + "Value: 32-bit mask controlling how attributes in each bit position are aggregated"
            + " for\\n"
            + "bonding groups consisting of multiple channels. A �1\u0027 in this mask for an\\n"
            + "attribute means that a bonding group attribute is considered to be the logical\\n"
            + "�AND\u0027 of the attribute bit for each channel. A �0\u0027 in this mask for an"
            + " attribute\\n"
            + "means that the bonding group is considered to have the logical �OR\u0027 of the\\n"
            + "attribute for each channel. This TLV uses the BITS Encoding convention\\n"
            + "where bit number 0 is the most significant bit of the mask.\\n"
            + "\\n"
            + "See Section 8.1.1 for how the Service Flow Required Attribute mask, Service Flow"
            + " Forbidden Attribute Mask, and\\n"
            + "Service Flow Attribute Aggregation Rule Mask control how service flows may be"
            + " assigned to particular channels or\\n"
            + "bonding"
            + " groups.\",\"SupportedVersion\":\"1.1\",\"Value\":\"\",\"Status\":\"0\",\"ParentTypeList\":{\"myArrayList\":[-1,24,33]},\"LengthMax\":4,\"LengthMin\":4,\"AreSubTypes\":false},{\"LevelType\":\"L2\",\"ByteLength\":\"1\",\"TlvName\":\"ApplicationIdentifier\",\"DataType\":\"byte_array\",\"Type\":\"34\",\"TlvDescription\":\"This"
            + " parameter allows for the configuration of a Cable Operator defined Application"
            + " Identifier for service flows,\\n"
            + "e.g., an Application Manager ID and Application Type as defined in [PCMM]. This"
            + " Application Identifier can be\\n"
            + "used to influence admission control or other policies in the CMTS that are outside"
            + " of the scope of this"
            + " specification.\",\"SupportedVersion\":\"1.1\",\"Value\":\"\",\"Status\":\"0\",\"ParentTypeList\":{\"myArrayList\":[-1,24,34]},\"LengthMax\":4,\"LengthMin\":4,\"AreSubTypes\":false},{\"LevelType\":\"L2\",\"ByteLength\":\"1\",\"TlvName\":\"UpstreamBufferControl\",\"DataType\":\"integer\",\"Type\":\"35\",\"TlvDescription\":\"The"
            + " Upstream Buffer Control provides a range for the maximum number of bytes that the"
            + " CM is permitted to\\n"
            + "enqueue for this upstream service flow\\n"
            + "The Upstream Buffer Control parameters impact upstream performance. While these"
            + " parameters can be applied to\\n"
            + "any service flow scheduling type, service flows that are not best effort typically"
            + " have optimized buffering\\n"
            + "implementations that make usage of the Upstream Buffer Control parameters"
            + " unnecessary. As a result, these\\n"
            + "parameters are only expected to be used with best effort service flows.\\n"
            + "The CM MUST support the Upstream Buffer Control encodings. The CM MUST ensure that"
            + " the size of the buffer\\n"
            + "of the upstream service flow is within the range defined by the Minimum Buffer and"
            + " Maximum Buffer\\n"
            + "parameters. The CM MUST reject an upstream service flow if it is unable to provide a"
            + " buffer within the range\\n"
            + "(inclusively) of bytes defined by the Minimum Buffer and Maximum Buffer parameters."
            + " If the Maximum Buffer has\\n"
            + "a value of no limit, then there is no restriction on the maximum size of the buffer."
            + " The CM MUST NOT queue more\\n"
            + "bytes for the service flow than the value defined by the Maximum Buffer. If the"
            + " Target Buffer is present and nonzero,\\n"
            + "the CM SHOULD set the size of the buffer for the upstream Service Flow to be equal"
            + " to the value of the Target\\n"
            + "Buffer parameter. A CM may have implementation-specific constraints that prevent"
            + " setting the size of the buffer to\\n"
            + "the Target Buffer value.\\n"
            + "The CM MUST support a buffer of at least 24 kibibytes (KiB) per upstream service"
            + " flow.\",\"SupportedVersion\":\"1.1\",\"Value\":\"\",\"Status\":\"0\",\"ParentTypeList\":{\"myArrayList\":[-1,24,35,3]},\"LengthMax\":0,\"LengthMin\":0,\"AreSubTypes\":true,\"SubTypeArray\":[{\"LevelType\":\"L3\",\"ByteLength\":\"1\",\"TlvName\":\"MinBuffer\",\"DataType\":\"byte_array\",\"Type\":\"1\",\"TlvDescription\":\"This"
            + " parameter defines a lower limit for the size of the buffer that is to be provided"
            + " for a service flow.\\n"
            + "If the device is unable to provide a buffer that meets the number of bytes defined"
            + " by the Minimum Buffer, the device\\n"
            + "is to reject the service flow.\\n"
            + "If this parameter is omitted, the Minimum Buffer defaults to a value of 0 which"
            + " indicates that there is no lower"
            + " limit.\",\"SupportedVersion\":\"1.1\",\"Value\":\"\",\"Status\":\"0\",\"ParentTypeList\":{\"myArrayList\":[-1,24,35,1]},\"LengthMax\":4,\"LengthMin\":4,\"AreSubTypes\":false},{\"LevelType\":\"L3\",\"ByteLength\":\"1\",\"TlvName\":\"TargetBuffer\",\"DataType\":\"byte_array\",\"Type\":\"2\",\"TlvDescription\":\"The"
            + " Target Buffer defines a desired value for the size of the buffer that is to be"
            + " provided for a service flow. This\\n"
            + "parameter exists for scenarios in which an ideal value for the size of the buffer"
            + " has been calculated in order to\\n"
            + "optimize an application. The specific algorithm by which this parameter might be"
            + " calculated is not specified here.\\n"
            + "If this parameter is omitted or set to a value of 0, the device selects any buffer"
            + " size within the range of the Minimum\\n"
            + "and Maximum Buffers, via a vendor specific"
            + " algorithm.\",\"SupportedVersion\":\"1.1\",\"Value\":\"\",\"Status\":\"0\",\"ParentTypeList\":{\"myArrayList\":[-1,24,35,2]},\"LengthMax\":4,\"LengthMin\":4,\"AreSubTypes\":false},{\"LevelType\":\"L3\",\"ByteLength\":\"1\",\"TlvName\":\"MaxBuffer\",\"DataType\":\"byte_array\",\"Type\":\"3\",\"TlvDescription\":\"This"
            + " parameter defines an upper limit for the size of the buffer that is to be provided"
            + " for a service flow.\\n"
            + "If this parameter is omitted, the Maximum Buffer defaults to a value of no"
            + " limit.\",\"SupportedVersion\":\"1.1\",\"Value\":\"\",\"Status\":\"0\",\"ParentTypeList\":{\"myArrayList\":[-1,24,35,3]},\"LengthMax\":4,\"LengthMin\":4,\"AreSubTypes\":false}]},{\"LevelType\":\"L2\",\"ByteLength\":\"1\",\"TlvName\":\"AggregateServiceFlowReference\",\"DataType\":\"byte_array\",\"Type\":\"36\",\"TlvDescription\":\"The"
            + " Aggregate Service Flow Reference is used to provide a reference to the higher level"
            + " Aggregate Service Flow;\\n"
            + "the use of this encoding is defined in the DPoE Specifications [DPOE-MULPIv1.0]."
            + " This is used to associate a\\n"
            + "Service Flow encoding to a higher level Aggregate Service Flow encoding.\\n"
            + "A CM MAY support the Aggregate Service Flow Reference. A CMTS MAY support the"
            + " Aggregate Service Flow\\n"
            + "Reference. If not supported this TLV is"
            + " ignored.\",\"SupportedVersion\":\"1.1\",\"Value\":\"\",\"Status\":\"0\",\"ParentTypeList\":{\"myArrayList\":[-1,24,36]},\"LengthMax\":0,\"LengthMin\":0,\"AreSubTypes\":false},{\"LevelType\":\"L2\",\"ByteLength\":\"1\",\"TlvName\":\"MESPReference\",\"DataType\":\"integer\",\"Type\":\"37\",\"TlvDescription\":\"The"
            + " MESP Reference is used to associate a Service Flow or Aggregate Service Flow"
            + " encoding with a set of Metro\\n"
            + "Ethernet Service Profile parameters described by an MESP Encoding (TLV 71). The"
            + " Metro Ethernet Service Profile\\n"
            + "(MESP) Reference within TLV [24/25/70/71] is used to provide a reference to a set of"
            + " QoS Parameters as defined by\\n"
            + "a particular MESP parameter set; the use of this encoding is defined in the DPoE"
            + " Specifications [DPOEMULPIv1.0].\\n"
            + "A CMTS MAY support the MESP Reference. A CM MAY support the MESP Reference. If not"
            + " supported this\\n"
            + "TLV is"
            + " ignored.\",\"SupportedVersion\":\"1.1\",\"Value\":\"\",\"Status\":\"0\",\"ParentTypeList\":{\"myArrayList\":[-1,24,37]},\"LengthMax\":2,\"LengthMin\":2,\"AreSubTypes\":false},{\"LevelType\":\"L2\",\"ByteLength\":\"1\",\"TlvName\":\"VendorSpecificQoS\",\"DataType\":\"integer\",\"Type\":\"43\",\"TlvDescription\":\"This"
            + " allows vendors to encode vendor-specific QoS parameters using the DOCSIS Extension"
            + " Field. The Vendor ID\\n"
            + "MUST be the first TLV embedded inside Vendor Specific QoS Parameters. If the first"
            + " TLV inside Vendor Specific\\n"
            + "QoS Parameters is not a Vendor ID, then the TLV MUST be discarded. (Refer to Annex"
            + " C.1.1.17).\",\"SupportedVersion\":\"1.1\",\"Value\":\"\",\"Status\":\"0\",\"ParentTypeList\":{\"myArrayList\":[-1,24,43]},\"LengthMax\":0,\"LengthMin\":0,\"AreSubTypes\":false}]}]";

    TlvAssembler tlvAssembler = null;

    try {
      tlvAssembler = new TlvAssembler(new JSONArray(JsonArray));
    } catch (JSONException e) {
      e.printStackTrace();
    }

    System.out.println("tlvAssembler: " + tlvAssembler.toString());
  }
}
